auto search for manage.py

diff --git a/.github/workflows/django.yml b/.github/workflows/django.yml
--- a/.github/workflows/django.yml
+++ b/.github/workflows/django.yml
@@ -36,5 +36,11 @@ jobs:
 
     - name: Run unit tests with coverage
       run: |
+        MANAGE_PATH=$(find . -type f -name "manage.py" | head -n 1)
+        if [ -z "$MANAGE_PATH" ]; then
+          echo "manage.py not found"
+          exit 1
+        fi
+        cd $(dirname "$MANAGE_PATH")
         coverage run manage.py test
         coverage report --fail-under=80
